#!/bin/bash
# This is a CodeRunner compile script. Compile scripts are used to compile
# code before being run using the run command specified in CodeRunner
# preferences. This script is invoked with the following properties:
#
# Current directory:	The directory of the source file being run
#
# Arguments $1-$n:		User-defined compile flags	
#
# Environment:			$CR_FILENAME	Filename of the source file being run
#						$CR_ENCODING	Encoding code of the source file
#						$CR_TMPDIR		Path of CodeRunner's temporary directory
#
# This script should have the following return values:
# 
# Exit status:			0 on success (CodeRunner will continue and execute run command)
#
# Output (stdout):		On success, one line of text which can be accessed
#						using the $compiler variable in the run command
#
# Output (stderr):		Anything outputted here will be displayed in
#						the CodeRunner console

# run rubber on the file specified by the 1st compiler flag of source file (the arg can contain relative path)
PATH="$PATH:/usr/texbin:/Library/TeX/texbin:/Library/TeX/Distributions/Programs/texbin"
# Set up output folder
outdir="output"
# Check if the user has specified a file to be run
if [ -z "$1" ]
then
	CR_PATH=$CR_FILENAME
else
	CR_PATH=$(realpath $(realpath $(dirname $CR_FILENAME))/$1)
fi
# Compute basename
name=$(basename "$CR_PATH")
name=${name%.*}
# Create output folder
output=$(mkdir "$outdir")
# Compile with rubber
output="$output $(rubber -s --into $outdir --pdf "$CR_PATH" 2>&1)"
status=$?
# Clean the files generated by compilation
output="$output $(mv "$outdir/$name.pdf" "$name.pdf" 2>&1)"
output="$output $(rm -r "$outdir" 2>&1)"
# Check if compilation was successful
if [ $status -eq 0 ]
then
	# Send PDF file path to console
	echo "$PWD/$name.pdf"
	echo $output &> "$PWD/${name}_log.txt"
else
	# Send compilation log to stderr
	>& 2 echo "$output"
fi
exit $status